<?php

namespace ContainerADH38bV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAnneeScolaireTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\AnneeScolaireType' shared autowired service.
     *
     * @return \App\Form\AnneeScolaireType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/AnneeScolaireType.php';

        return $container->privates['App\\Form\\AnneeScolaireType'] = new \App\Form\AnneeScolaireType();
    }
}
