<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Evaluation extends \App\Entity\Evaluation implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'college' => [parent::class, 'college', null],
        "\0".parent::class."\0".'dateEvaluation' => [parent::class, 'dateEvaluation', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'individu' => [parent::class, 'individu', null],
        "\0".parent::class."\0".'ligneEvaluations' => [parent::class, 'ligneEvaluations', null],
        "\0".parent::class."\0".'matiere' => [parent::class, 'matiere', null],
        "\0".parent::class."\0".'numero' => [parent::class, 'numero', null],
        "\0".parent::class."\0".'trimestre' => [parent::class, 'trimestre', null],
        'college' => [parent::class, 'college', null],
        'dateEvaluation' => [parent::class, 'dateEvaluation', null],
        'id' => [parent::class, 'id', null],
        'individu' => [parent::class, 'individu', null],
        'ligneEvaluations' => [parent::class, 'ligneEvaluations', null],
        'matiere' => [parent::class, 'matiere', null],
        'numero' => [parent::class, 'numero', null],
        'trimestre' => [parent::class, 'trimestre', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
