<?php

namespace ContainerXoGVT2t;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMainFormTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\MainFormType' shared autowired service.
     *
     * @return \App\Form\MainFormType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/MainFormType.php';

        return $container->privates['App\\Form\\MainFormType'] = new \App\Form\MainFormType();
    }
}
