<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXoGVT2t\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXoGVT2t/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXoGVT2t.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXoGVT2t\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXoGVT2t\App_KernelDevDebugContainer([
    'container.build_hash' => 'XoGVT2t',
    'container.build_id' => '39cb1183',
    'container.build_time' => 1709544113,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXoGVT2t');
